version: '3.1'
services:
  www:
    image: jeffdrumgod/lamp:2.0.0-apache-php-5.6
    expose:
      - "80/tcp"
      - "443/tcp"
    ports:
      - "80:80"
      - "443:443"
    environment:
      ENVIRONMENT: development
    volumes:
      - ./:/var/www/html
      - ./logs/apache2:/var/log/apache2
      - ./apache2/vhosts:/etc/apache2/from-host
      - ./apache2/certs:/etc/apache2/ssl/from-host
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:5.6
    expose:
      - "3306/tcp"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./datadir:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d